# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
permalink: /:year/:month/:title
defaults:
  -
    values:
      layout: "default"

# Custom values
social_urls:
  meetup: https://www.meetup.com/CocoaHeads-Stockholm/
  youtube: https://www.youtube.com/channel/UCdLzBDC5O6J3nJRb8m5PCaQ
  twitter: https://twitter.com/cocoaheadssthlm
  facebook: https://www.facebook.com/cocoaheadssthlm/
  slack: https://join.slack.com/t/cocoaheads-sthlm/shared_invite/zt-1rvlmy45e-MfSFLkMAFw_JLOcO1WzLng
  mastodon: https://mastodon.social/@cocoaheadssthlm
collections:
  - meetups
  - videos
  - jobs
